# Generated by Django 4.2.10 on 2024-02-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_customer_email_alter_booking_party_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='name',
        ),
    ]
