# Generated by Django 4.2.10 on 2024-02-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_customer_email_booking_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
    ]
