# Generated by Django 4.2.10 on 2024-02-29 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='party_size',
        ),
        migrations.AddField(
            model_name='table',
            name='number_of_seats',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
