# Generated by Django 4.2.10 on 2024-03-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
