# Generated by Django 4.2.10 on 2024-03-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_confirmation_date_booking_rejection_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='user',
        ),
    ]
